// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support Team",
            "url": "http://www.order-processor.example.com/support",
            "email": "support@order-processor.example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/orders": {
            "get": {
                "description": "Retrieve a paginated list of orders with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "List orders with pagination",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (starts from 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Filter by customer ID (UUID format)",
                        "name": "customer_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "pending",
                            "stock_verified",
                            "payment_processing",
                            "payment_completed",
                            "confirmed",
                            "failed",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "Filter by order status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Filter orders created after this date (RFC3339 format)",
                        "name": "created_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Filter orders created before this date (RFC3339 format)",
                        "name": "created_before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of orders",
                        "schema": {
                            "$ref": "#/definitions/dto.ListOrdersResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new order with the provided items. Returns 202 Accepted as the order will be processed asynchronously.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Idempotency key to prevent duplicate orders",
                        "name": "X-Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Order creation request",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Order created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrderResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict (e.g., duplicate idempotency key)",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Business logic error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/{id}": {
            "get": {
                "description": "Retrieve detailed information about a specific order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Order ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order details",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid order ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Performs a comprehensive health check of all system components including database, Redis, and RabbitMQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "System health check",
                "responses": {
                    "200": {
                        "description": "System is healthy",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "System is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/live": {
            "get": {
                "description": "Checks if the service is alive and responsive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Service liveness check",
                "responses": {
                    "200": {
                        "description": "Service is alive",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "Get paginated list of orders with optional filtering\nRetrieves a paginated list of orders with support for filtering by customer, status, and date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "List Orders",
                "parameters": [
                    {
                        "type": "string",
                        "default": "auto-generated",
                        "description": "Correlation ID for request tracing",
                        "name": "X-Correlation-ID",
                        "in": "header"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Filter by customer ID",
                        "name": "customer_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "pending",
                            "stock_verified",
                            "payment_processing",
                            "payment_completed",
                            "confirmed",
                            "failed",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "Filter by order status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Filter orders created from this date",
                        "name": "created_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Filter orders created until this date",
                        "name": "created_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of orders",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/OrderResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                },
                "x-correlation-id": true
            },
            "post": {
                "description": "Create a new order asynchronously\nThis endpoint accepts an order creation request, validates it, stores it in the database,\npublishes an event to the message queue, and returns immediately with 202 Accepted.\nThe actual order processing (stock verification, payment, etc.) happens asynchronously.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Create Order",
                "parameters": [
                    {
                        "type": "string",
                        "default": "auto-generated",
                        "description": "Correlation ID for request tracing",
                        "name": "X-Correlation-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Idempotency key to prevent duplicate requests",
                        "name": "X-Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Order creation request",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Order accepted for processing",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/OrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid input",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - Duplicate request (idempotency)",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity - Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                },
                "x-correlation-id": true,
                "x-idempotency": true
            }
        },
        "/orders/{id}": {
            "get": {
                "description": "Get order details by ID\nRetrieves detailed information about a specific order including its current status and processing history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get Order",
                "parameters": [
                    {
                        "type": "string",
                        "default": "auto-generated",
                        "description": "Correlation ID for request tracing",
                        "name": "X-Correlation-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/OrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid order ID format",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - Order not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                },
                "x-correlation-id": true
            }
        },
        "/ready": {
            "get": {
                "description": "Checks if the service is ready to accept traffic (lighter check than health)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Service readiness check",
                "responses": {
                    "200": {
                        "description": "Service is ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service is not ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorResponse": {
            "description": "Error response structure",
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string",
                    "example": "Bad Request"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request parameters"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                }
            }
        },
        "HealthCheckResponse": {
            "description": "Health check response structure",
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/ServiceHealthInfo"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m45s"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "OrderItem": {
            "description": "Order item structure",
            "type": "object",
            "required": [
                "product_id",
                "product_name",
                "quantity",
                "unit_price"
            ],
            "properties": {
                "product_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "product_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Wireless Headphones"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 2
                },
                "unit_price": {
                    "type": "number",
                    "example": 99.99
                }
            }
        },
        "OrderRequest": {
            "description": "Order creation request structure",
            "type": "object",
            "required": [
                "customer_email",
                "customer_id",
                "items"
            ],
            "properties": {
                "customer_id": {
                    "type": "string",
                    "x-order": "1",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "customer_email": {
                    "type": "string",
                    "x-order": "2",
                    "example": "customer@example.com"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/OrderItem"
                    },
                    "x-order": "3"
                }
            }
        },
        "OrderResponse": {
            "description": "Order response structure",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                },
                "customer_email": {
                    "type": "string",
                    "example": "customer@example.com"
                },
                "customer_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderItem"
                    }
                },
                "processed_at": {
                    "type": "string",
                    "example": "2023-09-19T10:35:00Z"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "stock_verified",
                        "payment_processing",
                        "payment_completed",
                        "confirmed",
                        "failed",
                        "cancelled"
                    ],
                    "example": "pending"
                },
                "total_amount": {
                    "type": "number",
                    "example": 199.98
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                }
            }
        },
        "PaginationResponse": {
            "description": "Pagination response structure",
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "data": {},
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "ServiceHealthInfo": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "last_check": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                },
                "latency": {
                    "type": "string",
                    "example": "2ms"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "SuccessResponse": {
            "description": "Success response structure",
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-09-19T10:30:00Z"
                }
            }
        },
        "dto.CreateOrderItemRequest": {
            "description": "Individual item details for order creation",
            "type": "object",
            "required": [
                "product_id",
                "product_name",
                "quantity",
                "unit_price"
            ],
            "properties": {
                "product_id": {
                    "description": "Product ID (UUID format)\n@Description Unique identifier for the product\n@Example \"456e7890-e89b-12d3-a456-426614174001\"",
                    "type": "string",
                    "example": "456e7890-e89b-12d3-a456-426614174001"
                },
                "product_name": {
                    "description": "Product name\n@Description Name/description of the product\n@Example \"Wireless Bluetooth Headphones\"",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Wireless Bluetooth Headphones"
                },
                "quantity": {
                    "description": "Quantity of the product\n@Description Number of units of this product in the order\n@Example 2",
                    "type": "integer",
                    "minimum": 1,
                    "example": 2
                },
                "unit_price": {
                    "description": "Unit price of the product in cents\n@Description Price per unit in cents (e.g., $19.99 = 1999)\n@Example 1999",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1999
                }
            }
        },
        "dto.CreateOrderRequest": {
            "description": "Request payload for creating a new order",
            "type": "object",
            "required": [
                "customer_email",
                "customer_id",
                "items"
            ],
            "properties": {
                "customer_email": {
                    "description": "Customer email address\n@Description Valid email address of the customer\n@Example \"customer@example.com\"",
                    "type": "string",
                    "example": "customer@example.com"
                },
                "customer_id": {
                    "description": "Customer ID (UUID format)\n@Description Unique identifier for the customer placing the order\n@Example \"123e4567-e89b-12d3-a456-426614174000\"",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "idempotency_key": {
                    "description": "Idempotency key for preventing duplicate orders\n@Description Optional idempotency key to prevent duplicate order creation\n@Example \"order-2024-001\"",
                    "type": "string",
                    "maxLength": 255,
                    "example": "order-2024-001"
                },
                "items": {
                    "description": "List of items in the order\n@Description Array of items to be included in the order",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.CreateOrderItemRequest"
                    }
                }
            }
        },
        "dto.CreateOrderResponse": {
            "description": "Response returned after successfully creating an order",
            "type": "object",
            "properties": {
                "correlation_id": {
                    "description": "Correlation ID for tracking\n@Description Correlation ID for tracking this order through the system\n@Example \"req_789e0123-e89b-12d3-a456-426614174002\"",
                    "type": "string",
                    "example": "req_789e0123-e89b-12d3-a456-426614174002"
                },
                "id": {
                    "description": "Order ID (UUID format)\n@Description Unique identifier for the newly created order\n@Example \"789e0123-e89b-12d3-a456-426614174002\"",
                    "type": "string",
                    "example": "789e0123-e89b-12d3-a456-426614174002"
                },
                "message": {
                    "description": "Message describing the result\n@Description Human-readable message about the order creation\n@Example \"Order created successfully and queued for processing\"",
                    "type": "string",
                    "example": "Order created successfully and queued for processing"
                },
                "status": {
                    "description": "Order status\n@Description Initial status of the created order\n@Example \"pending\"",
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "dto.ErrorResponse": {
            "description": "Standardized error response structure",
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code\n@Description Machine-readable error code for programmatic handling\n@Example \"VALIDATION_ERROR\"",
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "correlation_id": {
                    "description": "Correlation ID for tracking\n@Description Correlation ID for tracking this request through logs\n@Example \"req_789e0123-e89b-12d3-a456-426614174002\"",
                    "type": "string",
                    "example": "req_789e0123-e89b-12d3-a456-426614174002"
                },
                "details": {
                    "description": "Detailed error information\n@Description Additional details about the error",
                    "type": "object"
                },
                "message": {
                    "description": "Error message\n@Description Human-readable error message\n@Example \"Validation failed for one or more fields\"",
                    "type": "string",
                    "example": "Validation failed for one or more fields"
                },
                "path": {
                    "description": "Request path where error occurred\n@Description The API endpoint path where this error occurred\n@Example \"/api/v1/orders\"",
                    "type": "string",
                    "example": "/api/v1/orders"
                },
                "timestamp": {
                    "description": "Timestamp when error occurred\n@Description When this error occurred (RFC3339 format)\n@Example \"2024-01-15T10:30:00Z\"",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "dto.HealthComponentStatus": {
            "description": "Health status information for a system component",
            "type": "object",
            "properties": {
                "details": {
                    "description": "Additional component details\n@Description Additional information about the component",
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "description": "Error message if unhealthy\n@Description Error details if the component is not healthy\n@Example \"\"",
                    "type": "string",
                    "example": ""
                },
                "response_time_ms": {
                    "description": "Response time in milliseconds\n@Description How long it took to check this component\n@Example 5",
                    "type": "integer",
                    "example": 5
                },
                "status": {
                    "description": "Component status\n@Description Status of this component (healthy, degraded, unhealthy)\n@Example \"healthy\"",
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "dto.HealthComponents": {
            "description": "Health status information for each system component",
            "type": "object",
            "properties": {
                "cache": {
                    "description": "Redis cache health status\n@Description Redis cache connection status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.HealthComponentStatus"
                        }
                    ]
                },
                "database": {
                    "description": "Database health status\n@Description PostgreSQL database connection status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.HealthComponentStatus"
                        }
                    ]
                },
                "message_queue": {
                    "description": "RabbitMQ message queue health status\n@Description RabbitMQ message broker connection status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.HealthComponentStatus"
                        }
                    ]
                }
            }
        },
        "dto.HealthResponse": {
            "description": "System health check information",
            "type": "object",
            "properties": {
                "components": {
                    "description": "Individual component health status\n@Description Health status of individual system components",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.HealthComponents"
                        }
                    ]
                },
                "duration_ms": {
                    "description": "Request duration in milliseconds\n@Description How long this health check took to complete\n@Example 25",
                    "type": "integer",
                    "example": 25
                },
                "status": {
                    "description": "Overall system status\n@Description Overall health status of the system\n@Example \"healthy\"",
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "description": "Timestamp of the health check\n@Description When this health check was performed\n@Example \"2024-01-15T10:30:00Z\"",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "version": {
                    "description": "Service version\n@Description Version of the order processing service\n@Example \"1.0.0\"",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "dto.ListOrdersResponse": {
            "description": "Paginated response containing multiple orders",
            "type": "object",
            "properties": {
                "orders": {
                    "description": "List of orders\n@Description Array of orders matching the query criteria",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderResponse"
                    }
                },
                "pagination": {
                    "description": "Pagination information\n@Description Pagination metadata for the response",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.PaginationResponse"
                        }
                    ]
                }
            }
        },
        "dto.OrderItemResponse": {
            "description": "Individual item details within an order",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Item ID (UUID format)\n@Description Unique identifier for the order item\n@Example \"abc12345-e89b-12d3-a456-426614174003\"",
                    "type": "string",
                    "example": "abc12345-e89b-12d3-a456-426614174003"
                },
                "product_id": {
                    "description": "Product ID (UUID format)\n@Description Unique identifier for the product\n@Example \"456e7890-e89b-12d3-a456-426614174001\"",
                    "type": "string",
                    "example": "456e7890-e89b-12d3-a456-426614174001"
                },
                "product_name": {
                    "description": "Product name\n@Description Name/description of the product\n@Example \"Wireless Bluetooth Headphones\"",
                    "type": "string",
                    "example": "Wireless Bluetooth Headphones"
                },
                "quantity": {
                    "description": "Quantity ordered\n@Description Number of units of this product in the order\n@Example 2",
                    "type": "integer",
                    "example": 2
                },
                "total_price": {
                    "description": "Total price for this item in cents\n@Description Total price for this item (quantity * unit_price) in cents\n@Example 3998",
                    "type": "integer",
                    "example": 3998
                },
                "unit_price": {
                    "description": "Unit price in cents\n@Description Price per unit in cents (e.g., $19.99 = 1999)\n@Example 1999",
                    "type": "integer",
                    "example": 1999
                }
            }
        },
        "dto.OrderResponse": {
            "description": "Complete order information returned by the API",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Order creation timestamp\n@Description When the order was created (RFC3339 format)\n@Example \"2024-01-15T10:30:00Z\"",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "customer_email": {
                    "description": "Customer email address\n@Description Email address of the customer who placed the order\n@Example \"customer@example.com\"",
                    "type": "string",
                    "example": "customer@example.com"
                },
                "customer_id": {
                    "description": "Customer ID (UUID format)\n@Description Unique identifier for the customer who placed the order\n@Example \"123e4567-e89b-12d3-a456-426614174000\"",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "id": {
                    "description": "Order ID (UUID format)\n@Description Unique identifier for the order\n@Example \"789e0123-e89b-12d3-a456-426614174002\"",
                    "type": "string",
                    "example": "789e0123-e89b-12d3-a456-426614174002"
                },
                "items": {
                    "description": "Order items\n@Description List of items included in this order",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderItemResponse"
                    }
                },
                "processed_at": {
                    "description": "Order processing completion timestamp\n@Description When the order processing was completed (if applicable)\n@Example \"2024-01-15T10:45:00Z\"",
                    "type": "string",
                    "example": "2024-01-15T10:45:00Z"
                },
                "status": {
                    "description": "Order status\n@Description Current status of the order processing\n@Example \"pending\"",
                    "type": "string",
                    "example": "pending"
                },
                "total_amount": {
                    "description": "Total amount in cents\n@Description Total order amount in cents (e.g., $49.98 = 4998)\n@Example 4998",
                    "type": "integer",
                    "example": 4998
                },
                "updated_at": {
                    "description": "Order last update timestamp\n@Description When the order was last updated (RFC3339 format)\n@Example \"2024-01-15T10:35:00Z\"",
                    "type": "string",
                    "example": "2024-01-15T10:35:00Z"
                }
            }
        },
        "dto.PaginationResponse": {
            "description": "Pagination information for list responses",
            "type": "object",
            "properties": {
                "has_next": {
                    "description": "Whether there is a next page\n@Description Indicates if there are more pages available\n@Example true",
                    "type": "boolean",
                    "example": true
                },
                "has_prev": {
                    "description": "Whether there is a previous page\n@Description Indicates if there are previous pages available\n@Example false",
                    "type": "boolean",
                    "example": false
                },
                "limit": {
                    "description": "Items per page\n@Description Number of items per page\n@Example 20",
                    "type": "integer",
                    "example": 20
                },
                "page": {
                    "description": "Current page number\n@Description Current page number (starts from 1)\n@Example 1",
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "description": "Total number of items\n@Description Total number of items available across all pages\n@Example 150",
                    "type": "integer",
                    "example": 150
                },
                "total_pages": {
                    "description": "Total number of pages\n@Description Total number of pages available\n@Example 8",
                    "type": "integer",
                    "example": 8
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication. Format: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "x-extension-openapi": "{\"info\":{\"x-logo\":{\"url\":\"https://order-processor.example.com/logo.png\"}}}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Order Processing API",
	Description:      "A comprehensive REST API for asynchronous order processing with resilience patterns\nThis API provides endpoints for creating and managing orders in an asynchronous, resilient manner.\n\nFeatures:\n- Asynchronous order processing with messaging\n- Comprehensive error handling and logging\n- Rate limiting and idempotency support\n- Health checks and monitoring\n- Request/response validation\n- Correlation ID tracking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
