name: CI Pipeline

on:
  push:
    branches:
      [
        main,
        develop,
        task-17-refactor-tests-unitarios,
        task-18-tests-e2e-plan,
        refactor/e2e-real-dependencies,
        docs/api-testing-documentation,
      ]
  pull_request:
    branches: [main, develop]

env:
  NODE_ENV: test

jobs:
  # Job 1: Linting and Code Quality
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: TypeScript type checking
        run: npm run type-check

  # Job 2: Security Audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=high

      - name: Check for vulnerabilities
        run: npm audit --audit-level=critical

  # Job 3: Tests (Simplified to Node 20.x LTS only)
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          timeout 30s bash -c 'until nc -z localhost 5432; do sleep 1; done'

      - name: Wait for Redis
        run: |
          timeout 30s bash -c 'until nc -z localhost 6379; do sleep 1; done'

      - name: Debug environment variables
        run: |
          echo "DATABASE_HOST: ${DATABASE_HOST:-not set}"
          echo "DATABASE_PORT: ${DATABASE_PORT:-not set}"
          echo "DATABASE_NAME: ${DATABASE_NAME:-not set}"
          echo "DATABASE_USERNAME: ${DATABASE_USERNAME:-not set}"
          echo "DATABASE_USER: ${DATABASE_USER:-not set}"
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user

      - name: Run database migrations
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
        run: npm run migration:run

      - name: Run unit tests
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
        run: npm run test

      - name: Create E2E test database
        run: |
          PGPASSWORD=test_password psql -h localhost -U test_user -d test_db -c "DROP DATABASE IF EXISTS test_db_e2e;" || echo "No existing database to drop"
          PGPASSWORD=test_password psql -h localhost -U test_user -d test_db -c "CREATE DATABASE test_db_e2e;"

      - name: Run E2E tests
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db_e2e
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_DB: 1
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
          NODE_ENV: e2e
        run: npm run test:e2e

      - name: Generate coverage report
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Job 4: Build Application
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: dist
          key: build-${{ github.sha }}

  # Job 5: Quality Gate Check
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [test, build]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          timeout 30s bash -c 'until nc -z localhost 5432; do sleep 1; done'

      - name: Wait for Redis
        run: |
          timeout 30s bash -c 'until nc -z localhost 6379; do sleep 1; done'

      - name: Run database migrations for quality gate
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
        run: npm run migration:run

      - name: Check test coverage threshold
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
        run: |
          npm run test:cov
          echo "Checking coverage threshold..."
          # The coverage threshold is configured in jest.config.js

      - name: Create E2E test database for coverage
        run: |
          PGPASSWORD=test_password psql -h localhost -U test_user -d test_db -c "DROP DATABASE IF EXISTS test_db_e2e;" || echo "No existing database to drop"
          PGPASSWORD=test_password psql -h localhost -U test_user -d test_db -c "CREATE DATABASE test_db_e2e;"

      - name: Generate E2E coverage report
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db_e2e
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_USER: test_user
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_DB: 1
          JWT_SECRET: test-jwt-secret-key-for-testing
          ENCRYPTION_KEY: test-encryption-key-32-characters
          NODE_ENV: e2e
        run: npm run test:e2e:cov

      - name: Quality Gate Summary
        run: |
          echo "✅ All quality gates passed:"
          echo "- Linting: ESLint clean"
          echo "- Formatting: Prettier formatted"
          echo "- Types: TypeScript compilation successful"
          echo "- Security: No critical vulnerabilities"
          echo "- Tests: All unit tests passing"
          echo "- E2E Tests: All end-to-end tests passing"
          echo "- Coverage: Above threshold (Unit + E2E)"
          echo "- Build: Successful compilation"

  # Job 6: Notification on Success
  notify-success:
    name: Success Notification
    runs-on: ubuntu-latest
    needs: [quality-gate]
    if: success()
    steps:
      - name: Notify success
        run: |
          echo "🎉 CI Pipeline completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "All quality gates passed ✅"

  # Job 7: Notification on Failure
  notify-failure:
    name: Failure Notification
    runs-on: ubuntu-latest
    needs: [lint, security, test, build, quality-gate]
    if: failure()
    steps:
      - name: Notify failure
        run: |
          echo "❌ CI Pipeline failed!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Please check the failed jobs above."
